Action to create, test and publish wheels
falconry/falcon pull request #1754
Opened 2020-08-06 21:27 UTC by CaselIT

# Summary of Changes

Action to generate the wheels on release. Fixes https://github.com/falconry/falcon/issues/1281

TODO:
- [ ] remove various todos
- [ ] create upload sdist
- [x] crate wheels for linux (manylinux1,2010,2014)
- [x] create wheels for windows & osx
- [ ] create wheels for other supported platforms

2020-08-07 23:26 UTC, CaselIT commented
Regarding the compilation of cython files with cython, are the generated c files always the same regardless of the python 3 version?
I generate them with `cythonize -3 falcon/**/*.pyx`, but I'm not sure if it is ok

2020-08-08 13:00 UTC, CaselIT commented
For arm64, there are problems testing for python 3.5, since it tries to install `maturin` from source, and it requires rust to be installed. I think we could not provide a wheel for py 3.5 arm64. Or we skip testing it?

2020-08-09 13:15 UTC, CaselIT commented on setup.cfg
> +max-line-length = 100
This was a mistake in stashing. it will be removed once I revert the `tag_build`

2020-08-27 18:38 UTC, kgriffs commented
This is looking good! I added a token to the project secrets for the real index. Re the test index, I am waiting on an inquiry to see if we can take over https://test.pypi.org/project/falcon/ from the current owner.

2020-08-27 18:44 UTC, kgriffs commented
Question: Is there a convenient way to run the action in "test mode" which would flip it to point to the test index and disable the upload of the release assets? I am admittedly not familiar with GH actions to know if it would be easy to toggle this...

2020-08-28 13:08 UTC, CaselIT commented
> 
> 
> Question: Is there a convenient way to run the action in "test mode" which would flip it to point to the test index and disable the upload of the release assets? I am admittedly not familiar with GH actions to know if it would be easy to toggle this...

Not currently. I think it could be done by supporting a manual trigger and do the steps that upload the wheel to github and to pypi only if the triggering event is a release. 

Regarding changing the test pypi I don't know, since you need to both change the url and the token, since pypi and the test pipy are completely separate installation and do not share the accounts.
I guess that the `TWINE_REPOSITORY_URL` could be set to a github secret, so that the configuration would be:
- to use the official pypi: official token, remove the secret connected to the url.
- to use the test pypi: test token, create a secret connected to the `TWINE_REPOSITORY_URL` with the test url as value.

Another alternative (but I'm not sure if it's possible) is to add an if to the upload to pypi step to check for a particular message in the release message to disable it on demand?

2020-08-28 17:25 UTC, kgriffs commented
[Added TEST_PYPI_TOKEN secret]

2020-08-28 18:02 UTC, CaselIT commented
Ok, I'll do the update to the pr

2020-08-28 20:08 UTC, CaselIT commented
Updated. IIRC to test this this workflow should be on the default branch, so it's probably best to test on a fork, instead of the actual repo here.
The action trigger when a release (not a tag) is created.

I think we could keep the wheel creation targeted to test pypi for 1 or 2 of the alpha/beta release, check that everything works, then manually upload the wheel to the live pypi for that couple of test run. Then a follow on pr (maybe before the last rc) can change it target the actual pypi.

2020-08-29 15:51 UTC, vytas7 requested changes
As far as I am qualified (I haven't been involved in the Falcon release process too much), this looks great :+1: Bar one missing newline at the end of file, this is ready to go if @kgriffs is happy.

Btw, do `setup.cfg` additions also address https://github.com/falconry/falcon/issues/1652?

2020-08-29 15:51 UTC, vytas7 commented on setup.cfg
> +    ignore:cannot collect test class 'TestClient':pytest.PytestCollectionWarning
No newline at the end of file.

2020-08-29 16:13 UTC, CaselIT commented on setup.cfg
> +    ignore:cannot collect test class 'TestClient':pytest.PytestCollectionWarning
done.

2020-08-29 16:14 UTC, CaselIT commented
> Btw, do setup.cfg additions also address #1652? nvm I misread, you only added these to the respective envs.

That was the setup.cfg I use locally, since I like using pytest directly wrt tox. They indeed fix #1652 
They where published because I mistakenly stages all the file instead of only the relevant lines

2020-08-29 16:24 UTC, vytas7 commented
> They where published because I mistakenly stages all the file instead of only the relevant lines.

That explains. Because I swear I saw them! :slightly_smiling_face:

2020-08-29 16:25 UTC, vytas7 approved these changes
:100:

2020-10-16 18:12 UTC, CaselIT commented
It would be great if we could review and merge this, so we can tweak it in the next pre-releases

2020-10-16 18:18 UTC, vytas7 approved these changes

2020-11-21 23:28 UTC, kgriffs approved these changes

2020-11-21 23:28 UTC, merged

2020-11-22 08:52 UTC, CaselIT commented
Thanks for merging. I've made a follow up at #1787 that fixes an error with linux build that has come up after I created this