feat(testing.ASGIConductor): Implement an async test conductor for ASGI apps
falconry/falcon pull request #1766
Opened 2020-08-27 02:03 UTC by kgriffs

# Summary of Changes

This patch provides support for asynchronous interaction with the testing
client, including streaming updates to the response body.

This is mostly relevant for testing ASGI SSE and WebSocket (when implemented).

# Related Issues

#1634

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [ ] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [ ] Added **tests** for changed code.
- [ ] Prefixed code comments with GitHub nick and an appropriate prefix.
- [ ] Coding style is consistent with the rest of the framework.
- [ ] Updated **documentation** for changed code.
    - [ ] Added docstrings for any new classes, functions, or modules.
    - [ ] Updated docstrings for any modifications to existing code.
    - [ ] Updated both WSGI and ASGI docs (where applicable).
    - [ ] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [ ] Updated all relevant supporting documentation files under `docs/`.
    - [ ] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [ ] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/index.html) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

2020-08-27 02:05 UTC, kgriffs commented on docs/_static/custom.css
> +dl.function, dl.method, dl.attribute, dl.class {
I noticed some minor formatting issues while proofing the doc changes.

2020-08-27 02:07 UTC, kgriffs commented on falcon/asgi/app.py
> +_EVT_RESP_EOF = {'type': EventType.HTTP_RESP_BODY}
Since I was sprinkling yet another event string throughout the code (``'http.disconnect'``)

2020-08-27 02:09 UTC, kgriffs commented on falcon/asgi/app.py
> +            async def watch_disconnect():
While testing the conductor I discovered some subtle bugs related to handling the 'http.disconnect' event, and so I went ahead and fixed them as part of this PR.

2020-08-27 12:43 UTC, vytas7 commented
It seems that `typing.ContextManager` was introduced into the stdlib only in 3.7+, effectively making all py35, py36 and pypy environments fail.

2020-08-28 18:14 UTC, vytas7 requested changes
Looking good :+1:
I was just nitpicking on spelling and other cosmetics.

2020-08-28 18:14 UTC, vytas7 commented on falcon/testing/client.py
> +        :meth:`falcon.invoke_coroutine_sync`. Alternatively, you can try
To that end, I've also added the [`runs_sync`](https://falcon.readthedocs.io/en/latest/api/util.html#falcon.runs_sync) decorator.

2020-08-28 18:14 UTC, vytas7 commented on falcon/testing/helpers.py
> +        disconnect_at (int): The Unix timestamp after which to begin
Looking at the code, `float` seems to be implicitly supported too. And maybe it is even desirable to support fractional seconds here?

2020-08-28 18:14 UTC, vytas7 commented on tests/asgi/test_testing_asgi.py
> +    expected_elasped_min = 1
_elasped_ (sic) :arrow_right: _elapsed_

2020-08-28 21:27 UTC, CaselIT requested changes
looks promising

2020-08-28 21:27 UTC, CaselIT commented on falcon/testing/client.py
> +    def __init__(self, chunks: List[bytes]):
Nitpick. `chunks` could be a `Sequence[bytest]`

2020-08-28 21:27 UTC, CaselIT commented on falcon/testing/client.py
> +        pytest. As a workaround, the test can be adapted by wrapping it in
I think it should mention `pytest-asyncio` here since we nominate `pytest`

2020-08-28 21:27 UTC, CaselIT commented on falcon/testing/client.py
> +        self.app = app
`if not _is_asgi_app(app): raise ...`?

2020-08-28 21:27 UTC, CaselIT commented on falcon/testing/client.py
> +        if not getattr(self.app, '_ASGI', False):
should this be `_is_asgi_app`?

2020-08-28 23:11 UTC, kgriffs commented on falcon/asgi/app.py
> +            watcher.cancel()
I forgot to await the watcher after cancelling it... will fix this in the next round.

2020-08-29 00:01 UTC, kgriffs commented on tests/asgi/test_testing_asgi.py
> +    expected_elasped_min = 1
done

2020-08-29 09:17 UTC, CaselIT commented on falcon/asgi_spec.py
> +# Copyright 2019 by Kurt Griffiths
Personally I think supporting py3.5 is causing more problems that it's worth, so I'm in favour of dropping it.

For context [the downloads starts](https://pypistats.org/packages/falcon) says it's about 2% of total downloads.

@vytas7 @kgriffs thoughts?

2020-08-29 09:19 UTC, CaselIT approved these changes

2020-08-29 12:20 UTC, vytas7 commented on falcon/asgi_spec.py
> +# Copyright 2019 by Kurt Griffiths
IIRC I floated the idea on Gitter myself, but I would like to keep (obsolete) 3.5 support for 3.0, for two reasons: one, it is the default `python3` version on Ubuntu 16.04 LTS which is still somewhat ubiquitous in the server world, two, we have not announced anything wrt 3.5 deprecation before in the Falcon 2.0 release notes. And as I understand @kgriffs does not want to drop anything in a minor 3.x version.

But, as discussed, given the amount of things that are new to us in 3.0, we'll probably need to jump straight to 4.0 to afford for more breaking changes following 3.0. We can then drop 3.5 in Falcon 4.0.

2020-08-29 13:32 UTC, CaselIT commented on falcon/asgi_spec.py
> +# Copyright 2019 by Kurt Griffiths
Personally, I think we could just base our self on the official eol dates for python, aka 2020-09-13.

As a reference, numpy has already dropped support also for version 3.6.

2020-08-29 15:41 UTC, vytas7 approved these changes
:+1:

2020-08-29 15:42 UTC, merged