Potential bug-fixes using DeepSource
falconry/falcon pull request #1783
Opened 2020-11-16 08:00 UTC by withshubh

This PR fixes some of the quality issues raised by DeepSource on my fork of this repository.

**Some of them are:**
- **Performance Issues: 4**
- **Bug Risks: 14**
- **Anti-Patterns: 24**
- **Security: 6**

Take a quick look at all the issues caught by DeepSource for this repository [here](https://deepsource.io/gh/withshubh/falcon/issues/?category=recommended)

# Summary of Changes

- Change methods not using its bound instance to staticmethods
- use literal syntax instead of function calls to create data structure
- remove assert statement from non-test files
- refactor unnecessary 'else' / 'elif' when 'if' block has a 'return' statement 
- replace ternary syntax with if expression
- remove methods with unnecessary super delegation
- remove unnecessary generator

You can also have a look at the [configuration file](https://github.com/withshubh/falcon/blob/master/.deepsource.toml) I used for DeepSource Analysis.

If any of these issues that the DeepSource analysis found are critical for the codebase I'd suggest you to activate the analysis. You can trigger analysis on each PR once you integrate DeepSource in the repo. ⚡

Feel free to merge this PR if you wish to fix the issues.✨

2020-11-16 08:05 UTC, vytas7 commented
Hi, and thanks for this!

I'm, however, unsure if we want to refactor everything to `@staticmethod`. In some places, methods semantically belong to a class instance, even if they do not use self. In others, it probably does not warrant a change.

@kgriffs @CaselIT thoughts?

2020-11-16 08:53 UTC, CaselIT commented
I'm definitely -1 on the static method thing.

2020-11-16 20:54 UTC, vytas7 commented
Another comment unrelated to the use of `@staticmethod`.

Sorry to be blunt, but refactoring `assert` statements to manually raising `AssertionError` makes no sense to me.
The `assert` statement **is** the canonical way of [writing tests with `pytest`](https://docs.pytest.org/en/latest/getting-started.html#create-your-first-test). Manually raising an `AssertionError` in a conditional branch may even interfere with `pytest`'s ability to infer useful failure messages.

2020-11-16 20:58 UTC, vytas7 commented on falcon/util/uri.py
> +_HEX_TO_BYTE = {(a + b).encode(): bytes([int(a + b, 16)])
I guess this change we could actually keep. The old form probably could not use dict comprehension because it had to support Python 2.6.

2020-11-16 21:01 UTC, vytas7 commented on tests/test_sinks.py
> -    async def __call__(self, req, resp, **kwargs):
Reimplementing `__call__` is intended here (note the change from sync to `async`).

2020-11-16 21:14 UTC, vytas7 requested changes
Thank you once again for this initiative to improve our code quality.

However, as discussed in the above comments, we do not want to indiscriminately refactor the following:
* Functions not making use of `self` :arrow_right: `@staticmethod`. `@staticmethod` may at times semantically make sense, but more often than not, it is not the case in our codebase. Moreover, it does not offer any speed improvement (it actually may even incur a slight penalty).
* `assert` :arrow_right: manually raising an `AssertionError` in a branch statement -- we simply do not want this.
* `elif` after `return` or `raise` :arrow_right:  `if`. While I have nothing against the pattern itself, and actually use it, we need to discuss whether it is worth the effort (e.g., how do these alternatives compare performance wise?) refactoring. I.e., I'm actually not opposed to this one, but it is better to discuss this one separately.

I know it feels like harsh feedback... :imp:  But could you roll back refactoring of the 3 above patterns, and we could take a look at what's left. As noted on the PR, there are some good changes that we could actually be willing to keep.

Needless to say, @withshubh, You are also very welcome to discuss these changes with us on [our Gitter channels](https://falconframework.org/#sectionCommunity)!

2020-12-10 07:24 UTC, vytas7 commented
@withshubh just checking, if you are planning to continue work on this PR?

And I'm sorry to be blunt (again), but an _en masse_ `autopep8` refactoring is not something we want to accept as a side effect of this PR. We are looking into adopting `black`, `autopep8` or other alternatives, but that needs to be a separate, informed decision by the maintainer team. You'll have to revert those changes from your branch in order to proceed.

2020-12-10 08:12 UTC, withshubh commented
Hi @vytas7 :wave: 

It's okay for being blunt(again) :stuck_out_tongue: I'll fix this and update the PR. :sparkles:

2020-12-10 11:16 UTC, withshubh commented
Hi @vytas7 

Please have a look. :eyes:

2020-12-10 13:42 UTC, vytas7 requested changes
Please see inline comments.

2020-12-10 13:42 UTC, vytas7 commented on .deepsource.toml
> +version = 1
Please remove this file.
We have not decided on using DeepSource yet.

2020-12-10 13:42 UTC, vytas7 commented on falcon/util/structures.py
> +        self._store = {}
Please read the comment on line 33 to understand why, and revert this change.

2020-12-10 13:42 UTC, vytas7 commented on falcon/vendor/mimeparse/mimeparse.py
> +            fitness = 100 if type == target_type else 0
Let us revert these changes. Sensible they may be, we have vendored this module from https://github.com/dbtsai/python-mimeparse, and do not want to make any modifications unless absolutely necessary.

2020-12-10 13:42 UTC, vytas7 commented on falcon/vendor/mimeparse/mimeparse.py
> +    return weighted_matches[-1][2] if weighted_matches[-1][0][0] else ''
Let us revert these changes. Sensible they may be, we have vendored this module from https://github.com/dbtsai/python-mimeparse, and do not want to make any modifications unless absolutely necessary.

2020-12-11 07:41 UTC, withshubh commented
Hi @vytas7 

Now this PR contains just one fix:

- remove unnecessary generator

I'd like to know what are your thoughts regarding integrating the DeepSource.

2020-12-16 19:49 UTC, vytas7 requested changes
Let us please address PEP8 violations before merging this PR:
```
./falcon/util/uri.py:53:21: E127 continuation line over-indented for visual indent
./falcon/util/uri.py:54:21: E127 continuation line over-indented for visual indent
```

2020-12-19 08:04 UTC, withshubh commented
> Let us please address PEP8 violations before merging this PR:
> 
> ```
> ./falcon/util/uri.py:53:21: E127 continuation line over-indented for visual indent
> ./falcon/util/uri.py:54:21: E127 continuation line over-indented for visual indent
> ```

Done @vytas7 :sparkles:

2020-12-19 11:43 UTC, vytas7 approved these changes
Thanks for this!

Regarding DeepSource, my impression is that it is likely a very useful tool for a business project, or even a new open source library if DeepSource is agreed upon in advance.
However, for a highly specialized framework Falcon is, as you may have noticed, many "quality issues" exist there for a reason ("vendored" code, explicit test scenarios, deprecation strategies etc).
Moreover, another drawback is that DeepSource is not open, so we cannot easily integrate it into our offline development routines.

2020-12-19 11:46 UTC, merged