fix(ASGIRequestEventEmitter): emitter is very slow for large bodies
falconry/falcon pull request #1799
Opened 2020-12-09 18:32 UTC by kgriffs

2020-12-09 19:03 UTC, vytas7 requested changes
Not sure if it is due to any changes in branch toggling, or a change in request chunk mechanics, but codecov is now complaining these lines are not covered: https://github.com/falconry/falcon/blob/master/falcon/asgi/stream.py#L346-L348

2020-12-09 21:11 UTC, CaselIT submitted a review, later dismissed
other that vytas comment it look of to me

2020-12-10 05:10 UTC, kgriffs commented on tests/asgi/test_boundedstream_asgi.py
> +    import time
🤦

2020-12-10 06:39 UTC, vytas7 approved these changes

2020-12-10 07:16 UTC, CaselIT approved these changes

2020-12-10 07:18 UTC, merged