fix(ws): msgpack import error not handled
falconry/falcon pull request #1814
Opened 2020-12-13 01:36 UTC by kgriffs

# Summary of Changes

This patch modifies the default websocket binary media handler to not require msgpack upon instantiation.

2020-12-13 01:37 UTC, kgriffs commented on falcon/media/msgpack.py
> +            # TODO(kgriffs): There is probably a more elegant way to handle this situation
We can revisit this later; hopefully this is "good enough" for 3.0

2020-12-13 16:49 UTC, vytas7 requested changes
LGTM, but we need to actually submit coverage from a msgpack-free environment in _Actions_ too (or else we wouldn't get 100% coverage) before merging.

2020-12-13 18:49 UTC, CaselIT commented
I'm not too convinced by this approach. Why don't we create a fake handler that is used if there is no msgpack?
This fake handler would just raise an error.
When creating the default handlers we would then install this fake handler if there is no msg pack.

Something like:

```py

class MissingRequirementHandler:
  def __init__(self, library: str):
    self. library = library
  def _raise(self, *args, **kwargs):
    raise RuntimeError(f'Missing required library {self.library}')
  serialize = deserialize = _raise
```

2020-12-14 20:27 UTC, kgriffs commented
> LGTM, but we need to actually submit coverage from a msgpack-free environment in _Actions_ too (or else we wouldn't get 100% coverage) before merging.

Nice catch, I forgot to update GH actions. Will do.

2020-12-14 20:28 UTC, kgriffs commented
>  we would then install this fake handler 

That would be the more elegant approach. 👍

2020-12-14 20:31 UTC, CaselIT commented
Btw if we want to target 3.1 for the nicer approach, since it would not be a breaking change, I'm fine with this implementation for now :)

2020-12-14 21:33 UTC, vytas7 approved these changes
:+1:

2020-12-14 22:19 UTC, CaselIT approved these changes

2020-12-14 22:27 UTC, merged