Flake8 to ruff
falconry/falcon pull request #2236
Opened 2024-07-11 15:35 UTC by CaselIT

Replace flake8 with ruff

Not 100% sure all the options are the same, but no major changes were required

Fixes #2231

2024-07-11 17:40 UTC, vytas7 commented
Looks great 💯

Are you sure we are checking the import order though? I remember playing with that, and even when I configured `ruff` to follow the Google style we are currently using, it still generated a fair diff, and here I see no changes in that 🤔

2024-07-11 18:48 UTC, CaselIT commented
Honestly no, not sure if it activated thwt check

2024-07-13 09:35 UTC, vytas7 requested changes
It is shaping up for merging, we just need to revise these tutorial snippets.

2024-07-13 09:35 UTC, vytas7 commented on examples/asgilook/asgilook/store.py
> +import falcon
On the one hand, this makes sense from Falcon's perspective, but from the tutorial's perspective, `falcon` should be grouped just together with other 3rd parties just like `aiofiles`. But maybe it is hard to reconfigure Ruff just for the tutorials? Regardless, we need to make sure that other copypasted incarnations of this file are synced.

2024-07-13 09:35 UTC, vytas7 commented on examples/look/look/app.py
> -from .images import ImageStore, Resource
Same as for ASGI, we need to recheck if we don't need to sync the copypasted copies.

2024-07-13 13:54 UTC, vytas7 approved these changes
Looks good :100:
(Even if I missed anything, it should be mostly stylistic.)

2024-07-13 19:00 UTC, CaselIT commented
Here it goes then

2024-07-13 19:00 UTC, merged