change setup.py to make use of optional build_ext option
falconry/falcon pull request #2242
Opened 2024-07-13 12:09 UTC by CaselIT

This allows skipping the compilation of the c file if it fails for some reason, like the compiler is missing.
The build will still fail if cython can't generate the c file from the py/pyx file but that should be ok.
Fixes: #2237

2024-07-16 10:51 UTC, vytas7 requested changes
Looks good, and I've tested it to work well in different scenarios.
But apparently it is conflicted against `master`, we need to address these conflicts before merging.

2024-07-16 12:00 UTC, CaselIT commented
Thanks. Will merge with master soon!

2024-07-17 21:33 UTC, CaselIT commented
updated

2024-07-18 20:59 UTC, vytas7 approved these changes

2024-07-18 21:01 UTC, merged