Improve WS tutorial
falconry/falcon pull request #2257
Opened 2024-07-25 21:25 UTC by CaselIT

Some improvements to the ws tutorial

Fixes: #2255
Fixes: #2256

2024-07-26 06:26 UTC, CaselIT commented
@vytas7 I've added an interface only to the simpler echo ws endpoint, since I did not want to overcomplicate the html.

Let me know if you think it's enough

2024-07-26 07:41 UTC, CaselIT commented
note to self: we should probably replace or integrate the link at
https://github.com/falconry/falcon/blob/cbca63dc7739720eab856f48b32f9e782438be7a/falcon/asgi/ws.py#L239

with https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code

2024-08-06 07:08 UTC, vytas7 requested changes
Thanks! I wrote down a couple of comments inline.

Another thing we would need to go through is naming, it seems the tutorial directory is called `wslook`, but in the tutorial itself it is called differently.

2024-08-06 07:08 UTC, vytas7 commented on docs/user/tutorial-websockets.rst
> +- Falcon was configured to server a simple html page to use the echo websocket client for a browser.
~~to server~~ (sic) :arrow_right: _to serve_

2024-08-06 07:08 UTC, vytas7 commented on docs/user/tutorial-websockets.rst
> +- Falcon was configured to server a simple html page to use the echo websocket client for a browser.
Maybe capitalize HTML and WebSocket?

2024-08-06 07:08 UTC, vytas7 commented on examples/wslook/wslook/static/index.html
> +</html>
No newline at the end of file

2024-08-06 08:35 UTC, CaselIT commented
> the tutorial directory is called wslook, but in the tutorial itself it is called differently.

Do you habe a suggestion regarding the new name?

2024-08-06 12:30 UTC, vytas7 commented
> > the tutorial directory is called wslook, but in the tutorial itself it is called differently.
> 
> Do you habe a suggestion regarding the new name?

I don't have a particular preference, I just find it a bit confusing and error-prone that the same directory is called `wslook` in our repository, and [`asyncws`](https://falcon.readthedocs.io/en/latest/user/tutorial-websockets.html#first-steps) in the tutorial itself.

2024-08-06 13:14 UTC, CaselIT commented
makes sense. will think what of the two names makes more sense

2024-08-11 18:55 UTC, vytas7 approved these changes
LGTM, thanks! :100:

2024-08-11 18:56 UTC, merged