chore: deprecate TimezoneGMT class
falconry/falcon pull request #2302
Opened 2024-08-26 17:35 UTC by CaselIT

Fixes #2301

2024-08-26 19:26 UTC, vytas7 requested changes

2024-08-26 19:26 UTC, vytas7 commented on docs/_newsfragments/2301.newandimproved.rst
Release notes should not be worded in imperative as docstrings, just tell a story what has been done.

Moreover, I think deprecations better suit `.misc`, not `.newandimproved`.

2024-08-26 19:26 UTC, vytas7 commented on falcon/util/time.py
> +    def __init__(self) -> None:
Maybe we could just plop the `@deprecation.deprecated(...)` decorator on `__init__`, just like we do in `falcon.app.API`?

2024-08-26 19:26 UTC, vytas7 commented on tests/test_cookies.py
Not critical, but we have tests for various `util` functions, maybe it testing `TimezoneGMT` would better fit there than inside cookies? It is not really related to cookies.

2024-08-26 20:37 UTC, CaselIT commented on tests/test_cookies.py
it was there because it's only used there I think. will move them there

2024-08-27 08:19 UTC, vytas7 approved these changes
Thanks, it makes sense to deprecate this class indeed as it brings not much value over simply using UTC. :+1:

As discussed on Gitter, technically GMT and UTC are **not** the same, but CPython does not really support, itself, the subtle differences between the two time systems. (See also: https://github.com/python/cpython/issues/67762,)

2024-08-27 08:20 UTC, merged

2024-08-27 09:07 UTC, CaselIT commented
I don't actually think we need gmt in the cookies. It's very likely that if the specification ever mantated gmt it has now amended to mandata utc, since that's the one that's standard.