refactor (testing): preserve raw path in scope creation
falconry/falcon pull request #2331
Opened 2024-09-17 13:42 UTC by aarcex3

# Summary of Changes

Added a 'raw_path' key to the asgi scope in `create_scope` to preserve the path and keep consistency as per https://github.com/falconry/falcon/pull/2159

# Related Issues

 #2262

# Pull Request Checklist

- [x] Added **tests** for changed code.
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.

2024-09-17 13:44 UTC, aarcex3 commented
I have an issue with mypy, dunno if it's only me. It complains about line 680 in `testing/helpers.py`.

2024-09-17 14:32 UTC, vytas7 requested changes
Thanks for this initiative @aarcex3!

However, it seems there is a misunderstanding regarding the actual implementation.
In ASGI, raw path is presented as the [`raw_path`](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope) key inside `scope`. The value is a bytestring path, excluding any query string.

Furthermore, I think this improvement warrants a newsfragment, let's add one.

2024-09-18 14:15 UTC, aarcex3 commented
Hi @vytas7, I made the requested changes. 
Also, what is meant by _newsfragment_? Should I document the changes somewhere?

2024-10-05 16:33 UTC, vytas7 requested changes
It seems that some other gates are failing too, not just Mypy.

2024-10-05 16:33 UTC, vytas7 commented on falcon/testing/helpers.py
> +        # type: Dict[str, Union[bytes, str]]
Mypy says that this is invalid syntax, that's the main issue to start with I think.
Moreover, we shouldn't need type annotations in the comments now that we use `from __future__ import annotations` everywhere.

2024-10-06 08:50 UTC, vytas7 requested changes
Thanks for this improvement, it seems to function as intended now!

I have a couple of nitpicks wrt testing (commented inline); and we also need a news fragment for this issue. The file should be named `docs/_newsfragments/2262.newandimproved.rst`.

Unfortunately, we have no bandwidth to help shaping up this PR for the impending beta release that we are trying to haste in order to catch up with CPython 3.13, so we'll have to postpone this PR to Falcon 4.1. No specific action is required from you wrt this point, this is just for reference, that we will not be able to merge this PR until 4.0.0 stable is out.

2024-10-06 08:50 UTC, vytas7 commented on tests/asgi/test_testing_asgi.py
> +    path_no_queries = '/cache/http%3A%2F%2Ffalconframework.org/status'
It would be nice if we could reduce the amount of copy-paste in this test case by leveraging `pytest.mark.parametrize()`.

2024-10-06 08:50 UTC, vytas7 commented on tests/asgi/test_testing_asgi.py
See also the relevant test case in `tests/test_recipes.py`. It should be possible to update it to use and test the new functionality from this changeset.

2024-12-08 20:55 UTC, vytas7 submitted a review, later dismissed
Thanks once again for this improvement @aarcex3!
I have tweaked the proposed docs a bit more to my liking, and removed minor items from `test_recipes.py` that were obsoleted by your change.

2024-12-08 21:05 UTC, vytas7 approved these changes

2024-12-08 21:12 UTC, merged