feat(static): implement Etag rendering for static files
falconry/falcon pull request #2333
Opened 2024-09-18 15:42 UTC by dominik-air

# Summary of Changes

- Renders ETag for static files and includes it in the Response's headers.
- If `If_None_Match` header is present in Requests's headers and its ETag matches the file's ETag an `HTTP_304` status code is returned.

# Related Issues

Fixes #2243 

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [x] Added **tests** for changed code.
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [ ] Updated **documentation** for changed code.
    - [x] Added docstrings for any new classes, functions, or modules.
    - [x] Updated docstrings for any modifications to existing code.
    - [ ] Updated both WSGI and ASGI docs (where applicable).
    - [x] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [ ] Updated all relevant supporting documentation files under `docs/`.
    - [x] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [x] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/latest/quickstart.html#creating-news-fragments) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

2024-09-18 15:46 UTC, dominik-air commented
I still have to  go through the docs to see if any updates are needed there. As of now, I want to check with you if that's the intended implementation.

2024-10-04 16:45 UTC, vytas7 requested changes
As I understand, this is work-in-progress, so I didn't review the details, just provided general feedback on how we want to only call `fstat()` once per file.

2024-10-04 16:45 UTC, vytas7 commented on falcon/routing/static.py
> +    content_length = os.fstat(fh.fileno()).st_size
We don't want to run `os.fstat()` multiple times on the same file handle as it is a real syscall.
We only want to call it once per serving, and save the result in a variable.

2024-10-04 16:45 UTC, vytas7 commented on falcon/routing/static.py
> +                etag = _generate_etag(self._fallback_filename)
Same as above, we are already calling `fstat` and handling potential errors elsewhere in this file, we can just reuse the same result.

2025-01-02 10:01 UTC, vytas7 commented
Hi again @dominik-air :wave:, just checking if you intend to continue working on this issue?

2025-04-24 15:32 UTC, vytas7 commented
No worries @dominik-air, thanks for contributing this draft so far!
Unless you object though, we are going to close this PR for now as we trying to deal with our growing review backlog... :grimacing:
You can always open a new one if you get back to development of this improvement.

2025-04-24 15:32 UTC, closed without merging