Add option to enable xml serialization on errors.
falconry/falcon pull request #2356
Opened 2024-10-04 20:17 UTC by CaselIT

Fixes #2355

2024-10-05 14:45 UTC, vytas7 commented
Not directly related to this PR, but it seems we also need to update the wording of docs for [`App.set_error_serializer()`](https://falcon.readthedocs.io/en/latest/api/app.html#falcon.App.set_error_serializer) regarding media handlers.

2024-10-05 15:28 UTC, vytas7 requested changes
Looks good, just the docs need a bit polish, and I would prefer another name for the option itself (but I don't have very good suggestions).

2024-10-05 15:28 UTC, vytas7 commented on falcon/response.py
> +    """When ``False`` disables support for serializing http errors using XML when using
Suggested rewording
```rst
"""Set to ``False`` to disable automatic inclusion of the XML handler in the default error serializer (:arrow_left: link to its docs)
(default ``True``).

Enabling this option does not automatically render all error response in XML,
but only the client prefers (via the ``Accept`` request header) XML to JSON and other configured media handlers (link to docs?).
The browser, however, uses to prefer XML; so use this option exclude it from the supported media types.

Note:
    This option will be removed in Falcon 5.0 (with XML error serialization disabled by default).

Note:
    This option has no effect when a custom error serializer (link to docs?) is in use.
```

2024-10-05 16:46 UTC, CaselIT commented on falcon/http_error.py
> +    def to_xml(self) -> bytes:
I don't want the error serializer raising a deprecation warning, to the underscore version is needed

2024-10-05 16:47 UTC, CaselIT commented on docs/_newsfragments/2355.newandimproved.rst
> +Added a new flag :attr:`~falcon.ResponseOptions.enable_xml_error_serialization` that
could work

2024-10-05 16:48 UTC, vytas7 commented on falcon/http_error.py
> +    def to_xml(self) -> bytes:
Ah, makes sense!

2024-10-05 16:49 UTC, vytas7 commented on falcon/response.py
> +    """When ``False`` disables support for serializing http errors using XML when using
"but only if the client prefers" sorry

2024-10-06 08:14 UTC, vytas7 approved these changes
LGTM now, thanks for this improvement :+1:
We do want to get rid of any XML support out of the box, although we may want to add XML handlers in the future, either out of the box, or as a recipe, or an add-on library.

I would still like to polish docstrings and the proposed newsfragment, but I can try to address that in a followup PR.

**Edit**: got the ball rolling in https://github.com/falconry/falcon/pull/2358.

2024-10-06 08:15 UTC, merged