refactor: request-id to use contextvars
falconry/falcon pull request #2382
Opened 2024-10-20 22:19 UTC by EricGoulart

# Summary of Changes

Migrate the request-id handling from threading.local() to contextvars to improve compatibility with async coroutines and avoid issues with threading. This change ensures that request-id is properly tracked in asynchronous environments, providing more robust handling in both sync and async contexts.
Previously, threading.local() was used, which does not handle coroutines effectively. By using contextvars, we ensure that the request-id remains consistent across async calls.

# Related Issues

#2260

2024-10-21 16:15 UTC, vytas7 requested changes
Thanks for this improvement @EricGoulart, your code looks good. :+1:
Could you also try adding a couple of tests to `tests/test_recipes.py`? (Check out other recipe tests for inspiration.)

2024-10-21 16:24 UTC, EricGoulart commented
> Thanks for this improvement @EricGoulart, your code looks good. 👍 Could you also try adding a couple of tests to `tests/test_recipes.py`? (Check out other recipe tests for inspiration.)

Thank you for the feedback!  I'll go ahead and add a couple of tests to tests/test_recipes.py as suggested.

2024-10-31 13:41 UTC, vytas7 commented
Btw I don't know if you participating in Hacktoberfest, but this is already good enough to qualify, I'll add the label just in case.

2024-10-31 21:23 UTC, CaselIT approved these changes
thanks!

2024-11-05 15:42 UTC, vytas7 requested changes
It seems that something is still failing on import errors on your fork. Could you check?

2024-11-05 17:03 UTC, EricGoulart commented
Sure, I’ll check into it and make sure the import errors are resolved.

2024-11-10 13:51 UTC, closed without merging

2024-11-10 19:46 UTC, vytas7 commented
Hi @EricGoulart, did you intend to close this PR?

2024-11-10 19:48 UTC, vytas7 commented
Aha, I see you opened another one for the same changeset. We can continue the review process on that one instead.