Allow private networks
falconry/falcon pull request #2383
Opened 2024-10-21 17:37 UTC by zodecky

# Summary of Changes

Allow private networks as an option in CORS

# Related Issues

#2381 

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [ ] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [ ] Added **tests** for changed code.
- [ ] Prefixed code comments with GitHub nick and an appropriate prefix.
- [X] Coding style is consistent with the rest of the framework.
- [-] Updated **documentation** for changed code.
    - [ ] Added docstrings for any new classes, functions, or modules.
    - [ ] Updated docstrings for any modifications to existing code.
    - [ ] Updated both WSGI and ASGI docs (where applicable).
    - [ ] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [ ] Updated all relevant supporting documentation files under `docs/`.
    - [ ] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [ ] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/latest/quickstart.html#creating-news-fragments) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

2024-10-22 05:53 UTC, vytas7 requested changes
Something looks wrong... :confused: 
~~Have you changed line endings, or why does the whole file look as changed?~~ Aha, you added `middleware.py` as a top-level file... Please make changes to `falcon/middleware.py` instead.

Moreover, before merging, we'll need to add tests covering the new code, and a Towncrier newsfragment.

2024-10-31 02:23 UTC, zodecky commented
Ok! Thank you! I Will change that!

2024-11-06 15:58 UTC, zodecky commented
I added a test in TestCustomCorsMiddleware, but I am not sure if it was supposed to be in the TestCorsMiddleware
I put it in custom because it's an optional value and not default. Also I didnt change any of the existing tests, should I also add like 
assert 'Access-Control-Allow-Private-Network'.lower() not in h in the existing tests?

2024-11-10 20:03 UTC, vytas7 commented
It seems that our tests fail with the newly released [`websockets` 14.0](https://pypi.org/project/websockets/14.0/), this is not caused by your changes. We'll try to address this separately.

2024-11-10 23:02 UTC, zodecky commented
okk

2024-12-28 09:27 UTC, vytas7 requested changes
@zodecky thanks for the work on this issue so far.

Many tests are failing, could you take a look? Normally, it is more efficient to [run `tox` locally first](https://falcon.readthedocs.io/en/stable/community/contributing.html#pull-requests).

See also the inline comments.

2024-12-28 09:27 UTC, vytas7 commented on falcon/middleware.py
> -    Note:
Why did you remove this note? Please restore it, it is still valid.

2024-12-28 09:27 UTC, vytas7 commented on falcon/middleware.py
> +        allow_private_network: bool = False,
The new argument needs to be documented.

2025-02-08 17:47 UTC, vytas7 commented
@zodecky just checking, have you had a chance to address the above mentioned issues? And do you intend to continue working on this PR?

2025-03-14 12:12 UTC, vytas7 commented
In absence of a response, we are closing this for now. You can resubmit this at any time when the mentioned issues are fixed.

2025-03-14 20:55 UTC, CaselIT commented
@vytas7 maybe it could be salvaged by manually finishing this?

2025-03-15 08:46 UTC, closed without merging