typing: add middleware protocols
falconry/falcon pull request #2390
Opened 2024-10-26 12:26 UTC by jkmnt

# Summary of Changes

Typed the middleware classes with union of protocols.
Middleware class may conform to any protocol of the union to pass the type check

It's not perfect  due the nature of python's static duck typing, but better than the plain `object` ) Class may have correct signature for `process_request()`, but wrong signature for `process_response()`. It would be accepted since `MiddlewareWithProcessRequest`  says nothing about the `process_response`.

But if user explicitly states implemented protocols, then the typecheker will ensure strict conformance.
```python
class MyMiddleware(MiddlewareWithProcessRequest, MiddlewareWithProcessResponse):
    def process_request(...): ... # ok, pass
    def process_responce(...):  # won't pass (typo). process_response is required 
```

The protocols definitions are in the private `falcon._typing` module now. Should they be moved to the public `falcon.typing` to support this usecase ? 

The protocols names are long and noisy. Use some abbreviations ?

# Related Issues
#2372

2024-11-22 13:45 UTC, vytas7 commented
One thing that we need to investigate (not necessarily related to this change) is how to control annotations in Sphinx. Because if this new union of protocols gets evaluated/expanded, it really clutters the docs... :grimacing:

2025-01-11 22:42 UTC, vytas7 commented
As mentioned, I'll try to look into whether Sphinx can be tweaked not to unroll the whole union, and how different editors behave.

Because right now it is a bit of a showstopper wrt Sphinx:
![image](https://github.com/user-attachments/assets/254c904d-fa64-48cf-92a6-a42c28dbe9c8)

2025-01-18 18:01 UTC, vytas7 commented
It might be possible to resolve the Sphinx issue via [`autodoc_type_aliases`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_type_aliases), but haven't tried this myself.

2025-05-17 17:53 UTC, vytas7 requested changes
Thanks once again for prototyping this @jkmnt! I agree that this is much better than just `object`, especially given that in many cases middleware implements just a single method. :100: 

However, we need to find a more aesthetic solution than letting Sphinx unwrap these unions. I tried [autodoc_type_aliases](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_type_aliases), and unfortunately it doesn't really work as advertised... :grimacing: 

Another minor (and easy to fix) issue is that the async union seems to omit the WebSocket variants, probably by oversight.

2025-06-11 14:15 UTC, vytas7 commented
It seems that Sphinx doesn't traverse into very advanced secondary unions, and probably it doesn't traverse into `if TYPE_CHECKING:` either, so maybe it is possible to exploit these effects to prevent these mammoth unrolled forms from appearing.

**Edit**: No, this still doesn't seem to work for `App.__init__()` parameters...

**Edit2**: See this discussion that seems to touch upon similar issue(s) https://github.com/sphinx-doc/sphinx/issues/10785

2025-06-12 21:23 UTC, vytas7 requested changes
OK, I'm thinking to make the following changes:
* Rename `AsgiMiddleware` :arrow_right: `AsyncMiddleware`; I would like to avoid confusion with generic ASGI middleware.
* Fix `AsyncMiddleware` to include the accidentally omitted WebSocket methods.
* Move `Middleware` and `AsyncMiddleware` to `falcon.typing`, and document them as part of the public interface. Note that docstrings probably won't work, we'll need to write `.. class::` docs manually (see #2465 for more info).
* Keep all other new aliases confined to `falcon._typing` for now. Although I understand the value proposition of being able to annotate middleware more precisely, I doubt many users would go the extra mile; moreover, it is quite common that a middleware component implements just one or two methods from the interface, so I think this will practically be a major improvement over just [`object`].

Does that sound like an acceptable plan @CaselIT @jkmnt?

2025-07-02 15:47 UTC, vytas7 approved these changes
I have made improvements to this PR, but I cannot commit the changes despite having access to this PR, due to some GH glitch.

So let's merge this as-is, and I'll open a follow-up PR. (**Edit**: :arrow_right: #2472.)

Thanks once again for the effort @jkmnt!

2025-07-02 15:48 UTC, merged

2025-07-03 23:19 UTC, jkmnt commented
> I have made improvements to this PR, but I cannot commit the changes despite having access to this PR, due to some GH glitch.
> 
> So let's merge this as-is, and I'll open a follow-up PR. (**Edit**: ➡️ #2472.)
> 
> Thanks once again for the effort @jkmnt!

Looks good to me and it seems you're managed to commit the changes eventually.

PS: Hope to suggest more PRs to the Falcon after returning to the good old Python-land from the JS/TS hell )