refactor: update request-id recipe to use contextvars
falconry/falcon pull request #2404
Opened 2024-11-10 13:56 UTC by EricGoulart

# Summary of Changes

Migrate the request-id handling from threading.local() to contextvars to improve compatibility with async coroutines and avoid issues with threading. This change ensures that request-id is properly tracked in asynchronous environments, providing more robust handling in both sync and async contexts.
Previously, threading.local() was used, which does not handle coroutines effectively. By using contextvars, we ensure that the request-id remains consistent across async calls.

# Related Issues

Closes https://github.com/falconry/falcon/issues/2260.

2024-11-10 13:57 UTC, EricGoulart commented
I wanted to apologize for the confusion with my pull request. This is my first time contributing to a public repository, and I made a mistake with the process. I had previously opened a PR with the changes, but I accidentally closed it and am unable to reopen it.

2024-11-23 15:53 UTC, CaselIT submitted a review, later dismissed

2024-11-23 15:53 UTC, CaselIT commented on tests/test_recipes.py
> +        assert response.headers['X-Request-ID'] == response.json['request_id']
could also test that's the same as the value returned in the body

2024-11-24 16:32 UTC, vytas7 requested changes
Thanks, this looks good now at first glance. :+1:

However, many CI gates are still failing, could you please take a look?
(To save some time on review and CI rounds, it may be more efficient to run `tox` locally first on your side, and make sure everything is green.)

2024-11-24 16:32 UTC, vytas7 commented on docs/user/recipes/request-id.rst
> +normal request context, you can use a `contextvars`_ object to store
We could simply replace this with an Intersphinx link to the `contextvars` module, but this applies to the current version too, so not a requirement for merging this.

2024-12-27 10:33 UTC, vytas7 approved these changes
I fixed the import chain issues in the unit tests, thanks once again for this improvement @EricGoulart!

(I'll address two minor docs things remaining in a follow-up PR.)

2024-12-27 10:33 UTC, merged